# Generated by Django 3.2.4 on 2021-07-05 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSharingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement', models.FileField(blank=True, upload_to='uploaded_doc1/')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new_partner', 'NEW PARTNER'), ('old_partner', 'OLD PARTNER'), ('assistant_partner', 'ASSISTANT PARTNER')], max_length=50)),
                ('purchasing_owner', models.CharField(max_length=25)),
                ('is_name_approved', models.CharField(max_length=10)),
                ('region', models.CharField(choices=[('GL', 'GLOBAL'), ('EN', 'ENGLISH'), ('AR', 'ARABIC'), ('FR', 'FRENCH')], max_length=10)),
                ('country', models.CharField(choices=[('brazil', 'BRAZIL'), ('united_arab_emirates', 'UNITED ARAB EMIRATES'), ('united_stats_of_america', 'UNITED STATES OF AMERICA'), ('china', 'CHINA'), ('germany', 'GERMANY')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('consent_approach', models.CharField(choices=[('manager', 'MANAGER'), ('product_owner', 'PRODUCT OWNER'), ('product_manager', 'PRODUCT MANAGER')], max_length=50)),
                ('data_parameter', models.CharField(choices=[('update_report', 'UPDATE REPORT'), ('remove_params_from_report', 'REMOVE PARAMETERS FROM REPORT')], max_length=50)),
                ('data_share', models.CharField(choices=[('description_document', 'DESCRIPTION DOCUMENT'), ('high_level_design_document', 'HIGH LEVEL DESIGN DOCUMENT'), ('diagram_document', 'DIAGRAM DOCUMENT')], max_length=50)),
                ('iab_tcf_version', models.CharField(choices=[('v1.1', 'TCF v1.1'), ('v2.0', 'TCF v2.0')], max_length=50)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.datasharingdocument')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partnerinfo')),
            ],
            options={
                'unique_together': {('partner',)},
            },
        ),
    ]
