# Generated by Django 3.2.4 on 2021-07-06 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_datasharing_signed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contanct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_title', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=12)),
                ('contact_ext', models.CharField(max_length=4)),
                ('contact_type', models.CharField(max_length=10)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partnerinfo')),
            ],
        ),
    ]
